# Generated by Django 3.1.2 on 2020-11-13 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Categoria')),
                ('nombreCategoria', models.CharField(max_length=100, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=9, verbose_name='Rut Mecanico')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido1', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('apellido2', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('especialidad', models.CharField(max_length=9, verbose_name='Especialidad')),
                ('fecha_contrato', models.DateField(verbose_name='Fecha Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Servicio')),
                ('nombre', models.CharField(max_length=40, verbose_name='Marca')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('disponible', models.BooleanField(verbose_name='Disponibilidad')),
                ('precio', models.IntegerField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=6, verbose_name='Patente')),
                ('marca', models.CharField(max_length=40, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('litros', models.CharField(max_length=20, verbose_name='Litros')),
                ('configuracion', models.CharField(max_length=30, verbose_name='Configuracion')),
                ('kilometraje', models.IntegerField(verbose_name='Kilometraje')),
                ('transmision', models.CharField(max_length=20, verbose_name='Transmision')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('cliente', models.CharField(max_length=80, verbose_name='Nombre Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('idImagen', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Imagen')),
                ('texto', models.CharField(max_length=120, verbose_name='Texto Descriptivo')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Imagen')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('mecanico', models.CharField(default='mecanico', max_length=80, verbose_name='Nombre Mecanico')),
                ('archivo', models.ImageField(null=True, upload_to='registro_imagenes')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.categoria')),
            ],
        ),
    ]
