# Generated by Django 3.1.2 on 2020-11-06 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prueba', '0002_vehiculo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='cliente',
            field=models.ForeignKey(default='Nadie', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
