# Generated by Django 3.1.2 on 2020-11-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0004_auto_20201106_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='cliente',
            field=models.CharField(max_length=80, verbose_name='Nombre Cliente'),
        ),
    ]
